apiVersion: apps/v1
kind: Deployment
metadata:
   name: todoapp
     labels:
        app: todoapp
spec:
   replicas: 14
   strategy: 
       type: RollingUpdate
       rollingUpdate:
          maxSurge: 2   
          maxUnavailable: 2 
   template:
        metadata:
            name: todoapp
             labels: 
               app: todoapp      
        spec:
          containers:
              - name: http
                image: fazilasayyed/todo:latest 
                ports:
                     - name: http
                       containerPort: 80
                       protocol: TCP 
    selector:
        matchLabels:
            app: todoapp                
